### ISSUE TITLE
Group Deletion

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#1458]
We would like to delete groups. This should probably delete all of the students in the group as well as lessons and grades.
Since we are doing soft deletions, we should make sure to set the `deleted_at` property for all of those entities.

Items that are soft deleted will be eventually deleted by a background process but that is not a part of this ticket.

Undeletion is a part of this ticket. If a group gets undeleted we should restore all of the students, lessons, and grades that were deleted at the same time as the group. Items that were deleted at a different time should not be restored.

**Comment by KralMarko123** [comment]
# Done with #1849
