### ISSUE TITLE
Students missing in skill view when no skills

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#1770]
When a lesson is created in a subject that has no skills, the student table in the single lesson view is empty.

The reason is that we use `StudentLessonSummary` sql view for that table and it joins on `subject_summaries` view which is empty when the subject  has no skills.

**Comment by vikaskrsharma** [comment]
HI @tomca32, i can work on it.

**Comment by KralMarko123** [comment]
# Fixed with #1852
