### ISSUE TITLE
Deleted resources are preserved on the tablet

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#1823]
When a student or a group gets deleted, it is not deleted on the tablet. We should make sure to delete it from the tablet DB.

Core has a `deleted_at` property on students and groups that we can use for this. If it is `null` it means it's not deleted, otherwise there is a timestamp of deletion time.

Example group response:

Active group
`{"id":9,"group_name":"A","chapter_id":3,"deleted_at":null}`

Deleted group
`{"id":6,"group_name":"D","chapter_id":2,"deleted_at":"2023-12-21T02:19:04.883Z"}`

ORM entities should already have the deletedAt attribute

**Comment by KralMarko123** [comment]
Issue has been fixed with https://github.com/MindLeaps/Tracker-Mobile/pull/14
