### ISSUE TITLE
Ensure StudentLessonSummary reports correct data

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#1901]
`StudentLessonSummary` represents the summary of student's performance in a single lesson. It is identified by a `student_id` and a `lesson_id`.

It contains basic information about the student, first and last name, the identifiers of all the relations involved `student_id`, `group_id`, `lesson_id`, `subject_id`, and the calculations about the student's score: 
- `average_mark` - represents the average mark of the skills in which the student was graded, ungraded skills should not affect this score
- `skill_count` - represents the count of all the UNDELETED skills present in the subject
- `grade_count` - represents the count of grades (or graded UNDELETED skills) the  student received in that lesson
- `absent` - represents if the student was absent from the lesson. Although we have the `absences` table, we should not use it for this field. We want to eventually calculate absences from enrollments and the lack of grades, so for now we want to remove this field.
- `lesson_date` - A field that does not exist on this model yet but we're going to need it for visualizing individual student graphs so it needs to be introduced.

We want to make sure the calculations of all the scores are correct and to thoroughly test this through `StudentLessonSummary` model specs. Currently the tests present in `student_lesson_summary_spec` only test some `ActiveRecord` scopes. We need calculation correctness tests.

Correct average calculation is done by adding all the grade marks student received in the lesson and dividing it by the number of UNDELETED skills in which student was graded.

Example:
Subject has 3 skills
Student received 2 grades, marked: `3` and `4`
Average mark = (3 + 4) / 2 = 3.5

Testing should test the absence field, and include several different scenarios for testing average and skill and grade count. We should make sure they include multiple possible scenarios such as deleted skills, student graded in only some of the skills, student graded in all skills, student not graded at all.

So we want to:
- Remove `absent` field
- Introduce `lesson_date` field
- Ensure calculations are correct via thorough model testing

**Comment by KralMarko123** [comment]
# Closed with #1909
