### ISSUE TITLE
Ensure GroupLessonSummary reports correct data and takes enrollments into account

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#1902]
`GroupLessonSummary` is supposed to be represent a summary of a single lesson for a whole group. It is identified by a `group_id` and a `lesson_id`.

It contains the ids of all the relations involved: `group_id`, `lesson_id`, `chapter_id`, `subject_id`, as well as the `lesson_date`, `group_chapter_name`, and the following data:
 - `average_mark` - This currently represents the literal average of all the grades, however this should be changed, more below
 - `grade_count` the count of all the grades in the lesson

We need to change how the `average_mark` is calculated. Currently it just takes an average of all the grades, but we want it to be the average of the student's averages.

For example:
If we have 2 students with the following grades:
A: [4, 5, 6]
B: [1]

The old caculation would be 4 + 5 + 6 + 1 = 16 / 4 = `4` 
The new calculation should be (4 + 5 + 6) / 3 + 1/1 = 6 / 2 = `3`

We should only include the students that were graded in this calculation.

Performance might be tricky here, especially on larger datasets so this should be done in a SQL view that we are going to materialize into a table one day.

Calculations should only take into account UNDELETED students and skills. Deleted students or skills should not affect the calculation at all.

We need to test this thoroughly. `group_lesson_summary_spec` already contains some tests but some of them are almost certainly wrong. This needs to be tested with different scenarios, such as students being partially graded, absent, or deleted.

**Comment by KralMarko123** [comment]
# Done in #1934
