### ISSUE TITLE
Add a table of enrolled students in the group report

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#2032]
Group reports should start with a table of enrolled students. Remove `Group averages` subtitle from the beginning and start with a table of students pushing all other content down

Table should contain the following columns sorted by full name:

- MLID
- Full name in a single column ($LAST, $FIRST - `proper_name` method in student gives you this)
- Gender
- DOB
- Join Date - Date when student last joined the group
- Leave Date - Date when student last left the group - only display if not enrolled anymore

Break the page after this table. On the next page we will display an enrollment graph but that will be in another ticket

**Comment by KralMarko123** [comment]
# Done in #2038
