### ISSUE TITLE
Create enrollment chart in group reports

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#2033]
After the table of enrolled students and page break we should put an enrollment chart.

This chart should have alphabetically sorted students on the Y-axis and dates on the X-axis. For each student we should have a horizontal line during the periods while they were enrolled.

I have tried hacking this together with Chartist line and bar charts but wasnt successful so it will require a bit more research.

**Comment by tomca32** [comment]
Silly example but something in this style
![Image](https://github.com/user-attachments/assets/29e2f10a-d250-40a3-9cae-33da15f10bcd)

**Comment by KralMarko123** [comment]
# Implemented in #2048
