### ISSUE TITLE
Split group reports by subject

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#2055]
Currently, the group reports mix grades from all the subjects. This doesnt make much sense if there are lessons in more than 1 subject for that group.

The reports should be split by subject. For each subject we should start with the page break, then a subject title, followed by:

- These info boxes
![Image](https://github.com/user-attachments/assets/8c0ceceb-dfad-4bc4-b0b6-faed8a55c3da)
- Graphs
![Image](https://github.com/user-attachments/assets/4dad0ef4-a3ce-4a34-901b-4ede927c091e)
- Attendance graph
![Image](https://github.com/user-attachments/assets/9a61c4b9-789c-44b6-9e88-c0b17c95efbe)
- Performance table
![Image](https://github.com/user-attachments/assets/8f5db1a0-8ac1-4fa3-9c72-5f524e44c996)

**Comment by KralMarko123** [comment]
# Closed with #2060
