### ISSUE TITLE
Implement an Enrollments API

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#2126]
Currently, the Mobile app doesn't know anything about enrollments. However, with the changes coming to groups and enrollments, this is changing too.

We need to create an API for enrollments that the mobile app can query. This includes creating the routes, controller, as well as the policy for enrollments. The only endpoints we need are index and show...so `GET /enrollments` and `GET /enrollments/:id`. Having the option to scope it by student_id and group_id would also be helpful.

- Create `GET /enrollments` and `GET /enrollments/:id` endpoints
- Create a policy for the enrollments, make sure it is tested well. We probably only need policies for index and show since enrollments are not created directly for now. We do need scoping in the Policy to make sure we only return enrollments that the user has access to
- Have the index action on the new controller accept params for `group_id` and `student_id`. Every other endpoint also accepts `after_timestamp` so include that as well. `after_timestamp` logic is implemented in the `ApplicationRecord` superclass.
- Create EnrollmentSerializer
- Test the API through request specs and include matching on json schema

**Comment by KralMarko123** [comment]
# Implemented in #2130
