### ISSUE TITLE
Improve single Skill view

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#320]
Skill view can be found at`/skills/:id`
Steps to navigate to Skill View:
1. Click Skills in the nav menu
2. Click on any skill in the list

Currently, Skills view is very spartan with just the basic information displayed. It should be improved both design-wise to fit in with the rest of the application, as well as functionality wise so it can be a bit more useful.

Some ideas of what to include:
- List of subjects and organizations that are using the skill
- Number of Grades in the skill
- Average mark across all grades of the skill
- Bar chart of percentage grades in the skill

**Comment by KralMarko123** [comment]
# Closed with #2086
