### ISSUE TITLE
Display more information in the Lesson table

### ISSUE THREAD

**Issue by tomca32** [MindLeaps/tracker#342]
Lesson table (at /lessons) doesn't provide any information about the students, or grades, in it. We should expose the number of students in a group and the number of graded students as separate columns.

It might make sense to expose the average mark as a separate column too.

**Comment by an0n1mpulse** [comment]
I would like to pick this up :grin:

**Comment by tomca32** [comment]
Great!
I'm sure it will work with rbenv as well, as long as you use the ruby version described in the `.ruby-version` file.
